### ISSUE TITLE
SFTP server

### ISSUE THREAD

**Issue by PlayBoxTech** [AzuraCast/azuracast.com#15]
The documentation at: https://www.azuracast.com/help/faq_docker.html#access-files-via-sftp doesn't specify that the user name must be azuracast, it should specify that.

**Comment by ErnestPH** [comment]
> The documentation at: https://www.azuracast.com/help/faq_docker.html#access-files-via-sftp doesn't specify that the user name must be azuracast, it should specify that.

It is clearly stated in there… kindly read it back...

**Comment by Vaalyn** [comment]
@ErnestPH It is shown in there but it's not absolutely clear that you can't change the username. You can change the password and it will still work but not the username.

**Comment by ErnestPH** [comment]
Ahh yes. That's correct. I remembered I thought it was a bug until I found out it wasn't. I made a feature request for this one. Each station owner can use SFTP with their own username without checking other station's folder… I am not sure if it's been upvoted a lot though...

**Comment by SlvrEagle23** [comment]
Closing as we now directly provide SFTP connectivity within AzuraCast.
