### ISSUE TITLE
Demo installation redirects to AzuraCast website

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/azuracast.com#4]
When trying to open the demo installation with the link https://demo.azuracast.com/ you'll be redirected to the https://www.azuracast.com/demo.html page.

**Comment by SlvrEagle23** [comment]
@Vaalyn This is a known issue and happens at the top of every hour, as we're rebuilding the Docker instance. The redirection is intentional to avoid the site not serving at all.

**Comment by Vaalyn** [comment]
Ah okay, do you think we should add a page that tells the user to wait a moment and then try to access the demo installation again when this redirect happens? I found it quite confusing that I couldn't access the demo installation without any hint as to why.

**Comment by SlvrEagle23** [comment]
@Vaalyn We could do that...it's a Caddy server that's running to do that redirection, so it could serve a little HTML page.

**Comment by SlvrEagle23** [comment]
@Vaalyn I created a new static page on the main AzuraCast site that the demo will redirect to when it's reloading: https://www.azuracast.com/demo_reloading.html
