### ISSUE TITLE
Docker installation instructions seem to miss windows users

### ISSUE THREAD

**Issue by computamike** [AzuraCast/azuracast.com#64]
I've not tried this 100% - but I think that the shell script in the docs won't work under powershell?

In addition all of the steps assume that the user is running a linux machine - which is fine... but I think it should be possible to add Windows Installation instructions also.

I'll have a go at writing these up and submitting a pull request

**Comment by SC2Mitch** [comment]
Resolved ages ago

**Comment by computamike** [comment]
Hi @SC2Mitch - I'm just wondering: The docs have moved right? because there used to be a bunch of .md files (for example : 

this file here: https://github.com/AzuraCast/azuracast.com/blob/0a32969ac81b9c2f06d1cd2c243eff7f698da65f/docs/install/docker.md)

However, these files seem to have moved to https://github.com/AzuraCast/azuracast-docs? - I'm guessing that this repo now looks after just the azuracast.com site, and the documentation has moved to azuracast-docs?

**Comment by SC2Mitch** [comment]
Correct. This is now the main facing website and the docs repo will handle our documentation.
